name: MultiArchDockerBuild

on:
  push:
    branches:
      - master

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    env:
      DH_REGISTRY: docker.io
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: ${{ github.event.repository.name }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v4
        with:
          target: deploy
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.REPOSITORY }}:latest
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
